# Generated by Django 4.2.4 on 2023-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.IntegerField(verbose_name='Metai')),
                ('marke', models.CharField(max_length=200, verbose_name='Markė')),
                ('modelis', models.CharField(max_length=200, verbose_name='Modelis')),
                ('variklis', models.CharField(max_length=200, verbose_name='Variklis')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilio modeliai',
            },
        ),
    ]
