# Generated by Django 4.2.4 on 2023-08-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_alter_automobilis_options_paslauga_suma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paslauga',
            name='suma',
        ),
        migrations.AddField(
            model_name='paslauga',
            name='kaina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kaina'),
        ),
    ]
