# Generated by Django 4.2.4 on 2023-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_remove_paslauga_suma_paslauga_kaina'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtinta'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atšaukta')], default='p', max_length=1),
        ),
    ]
